service: time
provider:
  name: aws
  runtime: python3.8
functions:
  handler:
    package:
      artifact:
    handler: handler.handler
    events:
      - http:
          method: post
          path: /site_load_timer
plugins:
  - serverless-python-requirements
  - serverless-aws-documentation
custom:
  documentation:
    api:
      swagger: "2.0"
      info:
        title: "Sites load timer"
        description: "This is the API for getting time of load web pages. Based on asyncio."
        termsOfService: "http://swagger.io/terms/"
        contact:
          name: "Andrey Shapoval"
          email: "shapovalandrey27@google.com"
        version: "1.0.1"
      host: "lzmhux1fog.execute-api.us-east-1.amazonaws.com"
      basePath: "/dev"
      schemes:
        - "https"
        - "http"
      paths:
        /site_load_timer:
          post:
            summary: "Compute time of loading sites"
            description: "Returns 'url: time' pairs. In case of invalid url returns 'url: Invalid URL'"
            consumes:
              - "application/json"
            produces:
              - "application/json"
            parameters:
              - in: "body"
                name: "body"
                description: "Urls that need to be tested"
                required: true
                schema:
                  type: "array"
                  items:
                    type: "string"
            responses:
              "400":
                description: "Bad request data. There should be a list of urls in POST request body."
              "200":
                description: "'url: time' pairs. In case of invalid url returns 'url: Invalid URL'"
